name: Release
on:
  release:
    types: [ created, published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      # Build artifact using buildPlugin Gradle task
      - name: Build Plugin
        run: ./gradlew -PpluginVersion=${{ github.event.release.tag_name }} buildPlugin

      # Upload plugin artifact to make it available in the next jobs
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: plugin-artifact
          path: ./build/distributions/intellij-stepbuilder-codegen-plugin-${{ github.event.release.tag_name }}.zip
      - name: Publish Plugin to Jetbrains
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew -PpluginVersion=${{ github.event.release.tag_name }} publishPlugin
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} version {{ EVENT_PAYLOAD.release.name }} is out!'
